apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hw-mate-server
  namespace: mateapp
  labels:
    app: hw-mate-server
spec:
  selector:
    matchLabels:
      app: hw-mate-server
  template:
    metadata:
      labels:
        app: hw-mate-server
    spec:
      containers:
        - name: hw-mate-server
          image: busyboxplus:curl
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "200m"
              memory: "200Mi"
          ports:
            - containerPort: 80
              hostPort: 30009
          command:
              - /bin/sh
              - -c
              - |
                while true; do
                  curl todoapp-service.todoapp.svc.cluster.local/todolists/
                  sleep 5
                done